
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon May 31 08:24:15 PYT 2021
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 25;
  public static final int DISPLAY = 2;
  public static final int DIVIDE = 23;
  public static final int NOTEQUAL = 29;
  public static final int LPAREN = 30;
  public static final int INT = 11;
  public static final int MINUS = 21;
  public static final int STATIC = 5;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 37;
  public static final int AND = 26;
  public static final int LESSTHAN = 24;
  public static final int OR = 27;
  public static final int CLASS = 4;
  public static final int PLUS = 20;
  public static final int MAIN = 7;
  public static final int IF = 12;
  public static final int THIS = 17;
  public static final int DOT = 36;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int EQUAL = 28;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int COMA = 38;
  public static final int LCURLY = 34;
  public static final int BECOMES = 19;
  public static final int NUMBER = 40;
  public static final int VOID = 6;
  public static final int RCURLY = 35;
  public static final int TIMES = 22;
  public static final int ELSE = 13;
  public static final int LSQUARE = 32;
  public static final int RSQUARE = 33;
  public static final int WHILE = 14;
  public static final int SYSOUT = 15;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 9;
  public static final int STRING = 8;
  public static final int LENGTH = 16;
  public static final int IDENTIFIER = 39;
}

